[package]
name = "fuse-rs"
version = "0.1.0"
description = "A library to support Fuse server and virtio-fs device based on Linux Fuse ABI"
authors = ["Liu Bo <bo.liu@linux.alibaba.com>", "Liu Jiang <gerry@linux.alibaba.com>", "Peng Tao <bergwolf@hyper.sh>"]
license = "Apache-2.0 AND BSD-3-Clause"
edition = "2018"

[dependencies]
arc-swap = ">=0.4.4"
bimap = ">=0.4"
bitflags = ">=1.1.0"
libc = ">=0.2.67"
log = ">=0.4.6"
nix = "0.17.0"
vm-memory = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/vm-memory.git", branch = "master" }
vm-virtio = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/vm-virtio.git", branch = "master", optional = true }
vhost-rs = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/vhost.git", branch = "master", package = "vhost", optional = true }
snapshot = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/snapshot.git", branch = "master" }
versionize = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/versionize.git", branch = "master" }
versionize_derive = { git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/versionize_derive.git", branch = "master" }

[dev-dependencies.vm-memory]
git = "ssh://git@gitlab.alibaba-inc.com/rust-vmm/vm-memory.git"
branch = "master"
features = ["backend-mmap"]

[features]
fusedev = []
virtiofs = ["vm-virtio"]
vhost-user-fs = ["virtiofs", "vhost-rs/vhost-user-slave"]
with-serde = ["vm-memory/with-serde", "vhost-rs/with-serde"]

